fix: missing import and super_task default value (#321)
* fix: add missing imports for backwards compat.

* fix: redundant Metric

* fix: DP without supertasks

Traceback (most recent call last):
  File "/Users/luis/superai/dp-image_redaction/dp_image_redaction/image_redaction.py", line 138, in <module>
    dp.start_service(
  File "/Users/luis/superai/superai-sdk-private/superai/data_program/data_program.py", line 239, in start_service
    for task_schema in self._super_task_models:
TypeError: 'NoneType' object is not iterable

* fix: add empty list for super tasks in handler